### ISSUE TITLE
Add Github action to lint on push and pull request

### ISSUE THREAD

**Issue by jazhen** [waterthetrees/wtt_server#114]
For examples see:

- https://github.com/marketplace/actions/run-eslint
- https://github.com/samfromaway/Javascript-ES-Lint-Template/blob/master/.github/workflows/ci.yml

**Comment by Prakhar0409** [comment]
Hi @jazhen, can you assign this to me. I'd be happy to read and add a github action towards my hacktober contributions.

**Comment by jazhen** [comment]
Hi @Prakhar0409, sorry but this is essentially done. Just waiting for other changes to be approved. If you find something else that of interest feel free to ask.
