### ISSUE TITLE
createIdForTree causes "integer out of range" error on insert

### ISSUE THREAD

**Issue by jazhen** [waterthetrees/wtt_server#84]
### Context
Attempting to add a new tree fails with an "integer out of range" error. This is due to the createIdForTree function generating ids that are larger the int maximum in Postgres (i.e. -2147483648 to +2147483647). I was able to verify this by hard coding the inserted id. When the id was 2147483647 (i.e. the int max), the insert was successful. However, when the id was 2147483648 (i.e. 1 + the int max). the insert failed.

### Recreate the Issue
Sending a POST request to localhost:3002/api/trees when a body of 
```
{
  "city": "Montara",
  "common": "Oregon Crab Apple",
  "scientific": "Malus fusca",
  "genus": "Malus",
  "datePlanted": "2022-02-22",
  "dbh": "",
  "height": "",
  "address": "1208 Alamo St",
  "state": "CA",
  "zip": "94037",
  "neighborhood": "",
  "lng": -122.48007074505206,
  "lat": 37.63264661737338,
  "owner": "public",
  "who": "",
  "volunteer": "jasonzhen.mail",
  "notes": "",
  "health": "good",
  "email": "jasonzhen.mail@gmail.com",
  "idReference": "WTT202202227265902"
}
```
generates an id of 886478645782219 and has a response of 
```
{
  "error": "integer out of range"
}
```

### Possible Solution
We can change the treedata.id column to bigint type, which has a [range of -9223372036854775808 to +9223372036854775807](https://www.postgresql.org/docs/current/datatype-numeric.html).

[This resource](https://pganalyze.com/docs/log-insights/app-errors/U130) proposes one method of altering the column type.

### Screenshot
![image](https://user-images.githubusercontent.com/6326660/155265995-c0105a19-5fa4-4c8d-b5ec-beac899dfc5d.png)

**Comment by fwextensions** [comment]
Why not just store it as a string?  It's just an opaque unique identifier, and doesn't need to be treated as an int once it's created, as I understand it.
